In [1]:
###Python Giriş


In [2]:
name = "Faruk Yakut"

In [3]:
name

'Faruk Yakut'

In [4]:
print(name)

Faruk Yakut


In [5]:
sayi1 = 12
type(sayi1)

int

In [6]:
var1 = True
var = False
type(var1)

bool

In [7]:
rakam = 3.14
type(rakam)

float

In [8]:
rakam = int(3.14)
rakam

3

In [9]:
name =  input("İsim : ")
print(name)
type(name)

İsim : faruk
faruk


str

In [10]:
rakam = input("Yaşınız :" )
type(rakam)


Yaşınız :15


str

In [11]:
rakam = input("Yaşınız :" )
rakam = int(rakam)
type(rakam)

Yaşınız :15


int

In [12]:
2*3


6

In [13]:
2**3

8

In [14]:
pow(2,3)

8

In [15]:
## if-else

In [16]:
number = int(input("Bir sayı giriniz : "))
if number < 10:
    print("sayı 10'dan küçük")
else:
    print("sayı küçük 10")

Bir sayı giriniz : 5
sayı 10'dan küçük


In [17]:
### forDöngüsü

In [18]:
for i in range(5):
    print(i)

0
1
2
3
4


In [19]:
for i in range(5,10):
    print(i)

5
6
7
8
9


In [20]:
for i in range(5,15,2):
    print(i)

5
7
9
11
13


In [21]:
for i in range(5,0,-1):
    print(i)

5
4
3
2
1


In [22]:
name="faruk"

for j in name:
    print(j)

f
a
r
u
k


In [23]:
### 1' den 10' a kadar olan sayıların toplamı


In [25]:
toplam = 0
for i in range(11):
    toplam +=i

toplam    
    

55

In [26]:
###whilw

In [29]:
import random
secret_number = random.randint(1,10)
while True:
    guess = int(input("Tahmininizi giriniz : "))
    if guess == secret_number:
        print("Doğru sayi")
        break
    else:
        print("Yanlış tahmin")

Tahmininizi giriniz : 10
Yanlış tahmin
Tahmininizi giriniz : 9
Yanlış tahmin
Tahmininizi giriniz : 8
Yanlış tahmin
Tahmininizi giriniz : 7
Yanlış tahmin
Tahmininizi giriniz : 6
Yanlış tahmin
Tahmininizi giriniz : 5
Doğru sayi


In [30]:
###func

In [34]:
def toplama(rakam):
    toplam = 0
    for i in range(rakam+1):
        toplam += i
        
    print(toplam)    
        
        
toplama(10)
print(toplama(10))

55
55
None


In [33]:
def toplama2(rakam):
    toplam = 0
    for i in range(rakam+1):
        toplam += i
        
    return toplam   
        
        
toplama2(10)
print(toplama2(10))

55


In [35]:
###Listeler

In [39]:
liste = [1,2,3,4,5,6,7,8,9]

print(liste)

print(liste[-1])
print(liste[0])
print(liste[-2])
print(liste[-1:])




[1, 2, 3, 4, 5, 6, 7, 8, 9]
9
1
8
[9]


In [61]:
liste2 = [1,2,3,"elma","armut",True,False,["a",8,7]]
len(liste2)


8

In [47]:
liste2[-1]

['a', 8, 7]

In [48]:
liste2[-1][2]

7

In [49]:
liste2[0:5]

[1, 2, 3, 'elma', 'armut']

In [50]:
liste2[2:6]

[3, 'elma', 'armut', True]

In [51]:
liste2[:5]

[1, 2, 3, 'elma', 'armut']

In [52]:
liste2[:-1]

[1, 2, 3, 'elma', 'armut', True, False]

In [53]:
liste2[2:]

[3, 'elma', 'armut', True, False, ['a', 8, 7]]

In [54]:
liste2.append(11)

In [55]:
liste2

[1, 2, 3, 'elma', 'armut', True, False, ['a', 8, 7], 11]

In [62]:
liste2.insert(1,"fare")
liste2

[1, 'fare', 2, 3, 'elma', 'armut', True, False, ['a', 8, 7]]

In [63]:
del liste2[2]
liste2

[1, 'fare', 3, 'elma', 'armut', True, False, ['a', 8, 7]]

In [64]:
liste2.append([4,8,9])
liste2


[1, 'fare', 3, 'elma', 'armut', True, False, ['a', 8, 7], [4, 8, 9]]

In [65]:
liste2.extend([4,8,9])
liste2

[1, 'fare', 3, 'elma', 'armut', True, False, ['a', 8, 7], [4, 8, 9], 4, 8, 9]

In [66]:
liste2.remove("armut")
liste2

[1, 'fare', 3, 'elma', True, False, ['a', 8, 7], [4, 8, 9], 4, 8, 9]

In [67]:
"merhaba" in liste

False

In [68]:
"elma" in liste2

True

In [69]:
1 in liste2

True

In [70]:
liste2.extend([9,9,9])
liste2

[1, 'fare', 3, 'elma', True, False, ['a', 8, 7], [4, 8, 9], 4, 8, 9, 9, 9, 9]

In [72]:
while 9 in liste2:
    liste2.remove(9)
    
liste2    

[1, 'fare', 3, 'elma', True, False, ['a', 8, 7], [4, 8, 9], 4, 8]

In [73]:
liste3 = [9,4,6,7,2,3,1,5]
liste4 = ["kedi","pande","at","eşşek"]

In [75]:
liste3.sort()
liste3

[1, 2, 3, 4, 5, 6, 7, 9]

In [76]:
liste3.sort(reverse = True)
liste3

[9, 7, 6, 5, 4, 3, 2, 1]

In [77]:
liste4.sort()
liste4

['at', 'eşşek', 'kedi', 'pande']

In [78]:
###Sözlük (Dictionary) Veri Yapısı

In [79]:
myCat = {}
myCat

{}

In [80]:
myCat = {"size":"fat","age":2,"color":"white"}

In [81]:
myCat.keys()

dict_keys(['size', 'age', 'color'])

In [83]:
list(myCat.keys())

['size', 'age', 'color']

In [84]:
myCat.values()

dict_values(['fat', 2, 'white'])

In [85]:
myCat


{'size': 'fat', 'age': 2, 'color': 'white'}

In [86]:
myCat.items()

dict_items([('size', 'fat'), ('age', 2), ('color', 'white')])

In [88]:
ogrenciler={"isim" : ["ahmet","zeynep","veli"],
           "yas":[15,16,15],
           "boy":[160,165,185]}

In [89]:
ogrenciler

{'isim': ['ahmet', 'zeynep', 'veli'],
 'yas': [15, 16, 15],
 'boy': [160, 165, 185]}

In [90]:
ogrenciler["notlar"]=[75,80,95]

In [91]:
ogrenciler

{'isim': ['ahmet', 'zeynep', 'veli'],
 'yas': [15, 16, 15],
 'boy': [160, 165, 185],
 'notlar': [75, 80, 95]}

In [92]:
"isim" in ogrenciler.keys()

True

In [94]:
ogrenciler.values()

dict_values([['ahmet', 'zeynep', 'veli'], [15, 16, 15], [160, 165, 185], [75, 80, 95]])

In [95]:
"zeynep" in ogrenciler.values()

False

In [96]:
"zeynep" in ogrenciler["isim"]

True

In [97]:
for i in ogrenciler.keys():
    print(i)


isim
yas
boy
notlar


In [98]:
for i in ogrenciler.items():
    print(i)

('isim', ['ahmet', 'zeynep', 'veli'])
('yas', [15, 16, 15])
('boy', [160, 165, 185])
('notlar', [75, 80, 95])


In [104]:
#ahmet, 15,160,75

for i in ogrenciler.keys():
    print(ogrenciler[i][0], end=" ")


ahmet 15 160 75 

In [111]:
for i in range(len(ogrenciler.values())-1):
    print()
    for j in ogrenciler.keys():
            print(ogrenciler[j][i], end=" ")
        


ahmet 15 160 75 
zeynep 16 165 80 
veli 15 185 95 

In [114]:
###Numpy Kütüphanesi
liste1=[2,4,6]
liste2=[3,6,9]

liste3=[]
for i in range(len(liste1)):
    liste3.append(liste1[i]*liste2[i])
print(liste3)    

[6, 24, 54]


In [115]:
import numpy as np

In [116]:
a = np.array([2,4,6])
b = np.array([3,6,9])
print(a*b)

[ 6 24 54]


In [117]:
c = np.array([2,3,5,3.14])

In [118]:
c

array([2.  , 3.  , 5.  , 3.14])

In [119]:
d = np.array([2,3,5,3.14],dtype="int")

In [120]:
d

array([2, 3, 5, 3])

In [121]:
d2 = np.array([[1,2,3,],[4,5,6]])

In [122]:
d2

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
np.zeros(3)

array([0., 0., 0.])

In [124]:
np.zeros(3,dtype="int")

array([0, 0, 0])

In [125]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [128]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [129]:
np.full((4,2),3)

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [130]:
np.full(5,6)

array([6, 6, 6, 6, 6])

In [132]:
np.arange(0,15,4)

array([ 0,  4,  8, 12])

In [133]:
np.arange(0,14)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [135]:
np.linspace(0,14)

array([ 0.        ,  0.28571429,  0.57142857,  0.85714286,  1.14285714,
        1.42857143,  1.71428571,  2.        ,  2.28571429,  2.57142857,
        2.85714286,  3.14285714,  3.42857143,  3.71428571,  4.        ,
        4.28571429,  4.57142857,  4.85714286,  5.14285714,  5.42857143,
        5.71428571,  6.        ,  6.28571429,  6.57142857,  6.85714286,
        7.14285714,  7.42857143,  7.71428571,  8.        ,  8.28571429,
        8.57142857,  8.85714286,  9.14285714,  9.42857143,  9.71428571,
       10.        , 10.28571429, 10.57142857, 10.85714286, 11.14285714,
       11.42857143, 11.71428571, 12.        , 12.28571429, 12.57142857,
       12.85714286, 13.14285714, 13.42857143, 13.71428571, 14.        ])

In [136]:
np.linspace(0,14,1)

array([0.])

In [137]:
np.linspace(0,14,6)

array([ 0. ,  2.8,  5.6,  8.4, 11.2, 14. ])

In [138]:
?np.linspace

In [141]:
np.linspace(
    0,
    14,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)

array([ 0.        ,  0.28571429,  0.57142857,  0.85714286,  1.14285714,
        1.42857143,  1.71428571,  2.        ,  2.28571429,  2.57142857,
        2.85714286,  3.14285714,  3.42857143,  3.71428571,  4.        ,
        4.28571429,  4.57142857,  4.85714286,  5.14285714,  5.42857143,
        5.71428571,  6.        ,  6.28571429,  6.57142857,  6.85714286,
        7.14285714,  7.42857143,  7.71428571,  8.        ,  8.28571429,
        8.57142857,  8.85714286,  9.14285714,  9.42857143,  9.71428571,
       10.        , 10.28571429, 10.57142857, 10.85714286, 11.14285714,
       11.42857143, 11.71428571, 12.        , 12.28571429, 12.57142857,
       12.85714286, 13.14285714, 13.42857143, 13.71428571, 14.        ])

In [145]:
np.linspace(
    0,
    14,
    num=50,
    endpoint=True,
    retstep=False,
    dtype="int",
    axis=0,
)

array([ 0,  0,  0,  0,  1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  4,  4,  4,
        4,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  8,  8,  8,  8,  9,  9,
        9, 10, 10, 10, 10, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 14])

In [146]:
np.random.randint(0,10,(4,2))

array([[5, 5],
       [5, 6],
       [1, 7],
       [9, 5]])

In [152]:
np.random.random((3,2))

array([[0.87438422, 0.37072088],
       [0.2630727 , 0.74632318],
       [0.73360823, 0.80545238]])

In [158]:
a = np.random.randint(0,10,(4,2))
a

array([[8, 7],
       [0, 6],
       [6, 0],
       [2, 5]])

In [155]:
a[0]

array([6, 9])

In [159]:
a[3,1]

5

In [170]:
b = np.random.randint(0,20,(4,4))
b

array([[15,  6,  2, 18],
       [12, 19, 16, 14],
       [ 3, 19,  3, 10],
       [11,  9, 10,  6]])

In [163]:
b[:,3]

array([17, 14, 18,  9])

In [164]:
b[1:3,3]

array([14, 18])

In [171]:
c = b[1:4,3]
c

array([14, 10,  6])

In [167]:
b.shape

(4, 4)

In [172]:
d = c.reshape(-1,1)
d

array([[14],
       [10],
       [ 6]])

In [173]:
d.ndim


2

In [174]:
d3 = np.random.randint(0,100,6)
d3

array([56, 39, 16, 98, 56, 97])

In [175]:
d3.ndim

1

In [177]:
x = np.random.randint(0,100,(3,3))
x

array([[ 9, 43, 69],
       [ 6,  6, 24],
       [25, 30, 42]])

In [178]:
np.concatenate([x,x])

array([[ 9, 43, 69],
       [ 6,  6, 24],
       [25, 30, 42],
       [ 9, 43, 69],
       [ 6,  6, 24],
       [25, 30, 42]])

In [179]:
np.concatenate([x,x],axis=1)

array([[ 9, 43, 69,  9, 43, 69],
       [ 6,  6, 24,  6,  6, 24],
       [25, 30, 42, 25, 30, 42]])

In [180]:
x


array([[ 9, 43, 69],
       [ 6,  6, 24],
       [25, 30, 42]])

In [182]:
np.split(x,[2])

[array([[ 9, 43, 69],
        [ 6,  6, 24]]),
 array([[25, 30, 42]])]

In [183]:
np.hsplit(x,[2])

[array([[ 9, 43],
        [ 6,  6],
        [25, 30]]),
 array([[69],
        [24],
        [42]])]

In [184]:
y,z = np.hsplit(x,[2])

In [185]:
y

array([[ 9, 43],
       [ 6,  6],
       [25, 30]])

In [186]:
z

array([[69],
       [24],
       [42]])

In [187]:
t = np.random.randint(0,100,(5,5))
t

array([[93, 76, 58, 62, 24],
       [91, 20, 19, 95, 41],
       [56, 73, 56, 37, 63],
       [65, 32, 63, 11, 97],
       [32,  6, 47, 63, 59]])

In [188]:
np.hsplit(t,[2,4])

[array([[93, 76],
        [91, 20],
        [56, 73],
        [65, 32],
        [32,  6]]),
 array([[58, 62],
        [19, 95],
        [56, 37],
        [63, 11],
        [47, 63]]),
 array([[24],
        [41],
        [63],
        [97],
        [59]])]

In [189]:
np.split(t,[2,4])

[array([[93, 76, 58, 62, 24],
        [91, 20, 19, 95, 41]]),
 array([[56, 73, 56, 37, 63],
        [65, 32, 63, 11, 97]]),
 array([[32,  6, 47, 63, 59]])]

In [191]:
x2 = np.random.randint(1,10,(2,3))
x2

array([[1, 6, 2],
       [9, 1, 1]])

In [192]:
x2.max()

9

In [193]:
x2.sum()

20

In [195]:
np.square(x2)

array([[ 1, 36,  4],
       [81,  1,  1]])